// Class generated by LocalizationBuilder.cs
using UnityEditor;
using UnityEngine;

namespace ResourceLocalization
{
    /// <summary>
    /// Class for displaying localization fields.
    /// </summary>
    [CustomEditor(typeof(AudioClipLocalization)), TypeMetadata(typeof(AudioClip), "cs Script Icon")]
    public class AudioClipLocalizationEditor : LocalizationComponentEditor { }
}