// Class generated by LocalizationBuilder.cs
using UnityEditor;

namespace ResourceLocalization
{
    /// <summary>
    /// Class for displaying localization fields.
    /// </summary>
    [CustomEditor(typeof(AudioClipLocalization))]
    public class AudioClipLocalizationEditor : LocalizationComponentEditor { }
}