// Class generated by LocalizationBuilder.cs
using UnityEngine;
using UnityEngine.Events;

namespace ResourceLocalization
{
    public class AudioClipLocalization : LocalizationComponent
    {
        [System.Serializable] public class Handler : UnityEvent<AudioClip> { }
        [SerializeField, HideInInspector] private Handler handler;

        public override System.Type Type => typeof(AudioClip);

        public override void SetLocalizationData(object data) => handler?.Invoke((AudioClip)data);
    }
}